<?PHP
$pgSecurityLevel = 25;
if (!isset($gloConnected)):
    define('_RootPATH', '../');
    require('../wtk/wtkLogin.php');
endif;

$pgSQL =<<<SQLVAR
SELECT L.`Language`, L.`PrimaryText`, L.`NewText`, L.`MassUpdateId`,
    o.`LookupDisplay` AS `ConvertTo`
  FROM `wtkLanguage` L
    LEFT OUTER JOIN `wtkLookups` o ON o.`LookupType` = 'LangPref' AND o.`LookupValue` = L.`Language`
WHERE L.`UID` = ?
SQLVAR;
if ($gloWTKmode != 'ADD'):
    $gloForceRO = wtkPageReadOnlyCheck('/admin/languageEdit.php', $gloId);
    wtkSqlGetRow($pgSQL, [$gloId]);
    $pgLanguage = wtkSqlValue('Language');
    $pgAddMsg = '';
else:
    $pgLanguage = 'eng';
    $pgAddMsg  = '<p class="blue-text">Only Template Code translations should be added manually!';
    $pgAddMsg .= ' All other language translations should be generated by PHP wtkLang() calls.</p>';
endif;

$pgHtm =<<<htmVAR
<div class="container">
    <h4>Update Language</h4><br>
    <div class="card content b-shadow">
        <form id="wtkForm" name="wtkForm" method="POST">
            <span id="formMsg" class="red-text">$gloFormMsg</span>
            <div class="row">
                <div class="col s12">
                    $pgAddMsg
                    <p>By default, English is considered the primary language
                        for the website in regards to language translations.
                        Meaning you should enter how you want the website to look
                        in English, and then all translations will be done from
                        English to other languages.</p>
                    <p>You never need to <strong>add</strong> other languages here.  The
                      requests for generating the translations will automatically
                      be generated by surfing the site in the chosen language.
                      Then you can come here to either have AI generate the
                      translations or you could manually do so.  It is recommended
                      to let AI generate the translations then to have someone
                      knowledgeable in that language review and edit as necessary.</p>
                    <br>
                    <p>The `Template Code` is special for Single Page
                      Applications (SPA). In your <code class="code-text">wtk/htm/spa.htm</code>
                      page you will see code like this:</p>
<code class="code-text">
&lt;h5 id="langBugSent">Message Delivered&lt;/h5>
</code>
                    <p>In the wtkLanguage data there is a `Template Code` of "BugSent".
                    When a user changes their language preference, the SPA page
                    will automatically be updated by an AJAX call which loops through looking
                    for any `id` that starts with "lang" and has the `Template Code`
                    and will exchange it with the translated text.  In the above example,
                    it would find `langBugSent`.</p>
                    <p>You can add as many of these in your spa.htm page as you like,
                        then just add here with the associated `Template Code`.<p>
                    <p>Note: automated language translation is turned off for this WTK Back Office.
                      To enable, simple change one line in /wtk/lib/Security.php:</p>
                    <p><code class="code-text">&dollar;fncPos = strpos(&dollar;_SERVER['PHP_SELF'], 'admin/');  // do not build translations for Admin site</code></p>
                    <br><hr><br>
                </div>

htmVAR;

if ($gloWTKmode == 'ADD'):
    $pgHtm .= '<div class="col m4 s12"><h6>Template Code:</h6></div>' . "\n";
    $pgHtm .= wtkFormText('wtkLanguage', 'MassUpdateId', 'text', 'Template Code', 'm4 s12','Y','should not start with `lang`');
    $pgHtm .= wtkFormPrimeField('wtkLanguage', 'Language', 'eng');
    $pgHtm .= '<div class="col s12"><br>&nbsp;</div>' . "\n";
else:
    if (($gloUserSecLevel >= 90) && ($pgLanguage == 'eng')): // Owner or CTO level
        $pgHtm .= '<div class="col m4 s12"><h6>Template Code:</h6></div>' . "\n";
        $pgHtm .= wtkFormText('wtkLanguage', 'MassUpdateId', 'text', 'Template Code', 'm4 s12','N','should not start with `lang`');
        $pgHtm .= '<div class="col s12"><br>&nbsp;</div>' . "\n";
    else:
        $pgMassUpdateId = wtkSqlValue('MassUpdateId');
        if ($pgMassUpdateId != ''):
            $pgHtm .= '<div class="col m4 s12"><h6>Template Code:</h6></div>' . "\n";
            $pgHtm .= '<div class="col m8 s12">' . $pgMassUpdateId . '</div>' . "\n";
            $pgHtm .= '<div class="col s12"><br>&nbsp;</div>' . "\n";
        endif;
    endif;  // Owner or CTO level
endif;

if ($pgLanguage == 'eng'):
    $pgHtm .= '<div class="col m4 s12">' . "\n";
    $pgHtm .= '<h6>English Version:</h6>';
    $pgHtm .= 'will translate from this to other language</div>' . "\n";
    $pgHtm .= wtkFormText('wtkLanguage', 'NewText', 'text', 'English Text', 'm8 s12', 'Y');
else:
    $pgHtm .= '<div class="col m4 s12"><h6>English version to translate from:</h6></div>' . "\n";
    $pgHtm .= '<div class="col m8 s12">' . wtkSqlValue('PrimaryText') . '</div>' . "\n";
    $pgConvertTo = wtkSqlValue('ConvertTo');
    $pgHtm .= '<div class="col s12"><br>&nbsp;</div>' . "\n";
    $pgHtm .= '<div class="col m4 s12"><h6>Translating to ' . $pgConvertTo . ':</h6></div>';
    $pgTmp  = wtkFormText('wtkLanguage', 'NewText', 'text', 'Will Translate Into', 'm8 s12" style="margin-top:-20px');
    $pgHtm .= wtkReplace($pgTmp, '<label class="active"','<label class="hide"');
endif;

$pgHtm .= wtkFormHidden('ID1', $gloId);
$pgHtm .= wtkFormHidden('UID', wtkEncode('UID'));
$pgHtm .= wtkFormHidden('wtkMode', $gloWTKmode);
$pgHtm .= wtkFormHidden('wtkGoToURL', '../../admin/languageList.php');
$pgHtm .= '            </div>' . "\n";
$pgHtm .= wtkUpdateBtns() . "\n";
$pgHtm .= wtkFormWriteUpdField();

$pgHtm .=<<<htmVAR
        </form>
    </div>
</div>
htmVAR;
echo $pgHtm;
exit;
?>
